// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpDITuq1gt4ESD6RKIezhf4nhX37aBB4',
    appId: '1:911247332711:web:2e7b937b206b01b1da0bc2',
    messagingSenderId: '911247332711',
    projectId: 'water-piping',
    authDomain: 'water-piping.firebaseapp.com',
    storageBucket: 'water-piping.firebasestorage.app',
    measurementId: 'G-6XB33LYCVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6O7zuCyFvbT3V3VkOWYKxJ2_eBeBuzp0',
    appId: '1:911247332711:android:725df71a9470ea9dda0bc2',
    messagingSenderId: '911247332711',
    projectId: 'water-piping',
    storageBucket: 'water-piping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIG5F019RWqArxv_eEzB6x-7_piNBuwiQ',
    appId: '1:911247332711:ios:48f67a72b9779c08da0bc2',
    messagingSenderId: '911247332711',
    projectId: 'water-piping',
    storageBucket: 'water-piping.firebasestorage.app',
    iosBundleId: 'com.example.waterPipeMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIG5F019RWqArxv_eEzB6x-7_piNBuwiQ',
    appId: '1:911247332711:ios:48f67a72b9779c08da0bc2',
    messagingSenderId: '911247332711',
    projectId: 'water-piping',
    storageBucket: 'water-piping.firebasestorage.app',
    iosBundleId: 'com.example.waterPipeMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPpDITuq1gt4ESD6RKIezhf4nhX37aBB4',
    appId: '1:911247332711:web:17d9124f46388983da0bc2',
    messagingSenderId: '911247332711',
    projectId: 'water-piping',
    authDomain: 'water-piping.firebaseapp.com',
    storageBucket: 'water-piping.firebasestorage.app',
    measurementId: 'G-30PK74MG8V',
  );
}
